=== rubengomes8/IST-POO/src/parsing/simulation.dtd
<!DOCTYPE SIMULATION [

<!ELEMENT simulation (graph+,events+)>

<!ATTLIST simulation 
	finalinst 	CDATA 	#REQUIRED
	antcolsize 	CDATA 	#REQUIRED
	plevel 		CDATA 	#REQUIRED
>

<!ELEMENT graph (node+)>

<!ATTLIST graph 
	nbnodes 	CDATA 	#REQUIRED
	nestnode 	CDATA 	#REQUIRED
>

<!ELEMENT node (#PCDATA)>

<!ATTLIST node nodeidx CDATA #REQUIRED>


<!ELEMENT weight (#PCDATA)>

<!ATTLIST weight targetnode CDATA #REQUIRED>



<!ELEMENT events (move+,evaporation+)>

<!ELEMENT move (#PCDATA)>

<!ELEMENT evaporation (#PCDATA)>


<!ATTLIST move 
	alpha 	CDATA 	#REQUIRED
	beta 	CDATA 	#REQUIRED
	delta 	CDATA 	#REQUIRED
>

<!ATTLIST evaporation 
	eta 	CDATA 	#REQUIRED
	rho 	CDATA 	#REQUIRED
>

]>

=== rubengomes8/IST-POO/src/Testing_set/TESTS/test_3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE simulation SYSTEM "simulation.dtd">
<simulation finalinst="2000.0" antcolsize="1" plevel="0.5">
  <graph nbnodes="10" nestnode="1">
      <node nodeidx="1">
          <weight targetnode="2">1</weight>
          <weight targetnode="3">1</weight>
          <weight targetnode="4">1.5</weight>
      </node>
      <node nodeidx="2">
          <weight targetnode="3">2</weight>
          <weight targetnode="4">4</weight>
          <weight targetnode="5">3</weight>
      </node>
      <node nodeidx="3">
          <weight targetnode="4">3</weight>
          <weight targetnode="6">3</weight>
          <weight targetnode="8">4</weight>
          <weight targetnode="10">5</weight>
      </node>
      <node nodeidx="4">
          <weight targetnode="5">1.5</weight>
          <weight targetnode="6">3</weight>
          <weight targetnode="7">4</weight>
      </node>
      <node nodeidx="5">
          <weight targetnode="6">1</weight>
          <weight targetnode="7">1</weight>
      </node>
      <node nodeidx="6">
          <weight targetnode="7">2</weight>
          <weight targetnode="8">4</weight>
          <weight targetnode="10">3</weight>
          <weight targetnode="9">1</weight>
      </node>
      <node nodeidx="8">
          <weight targetnode="9">3</weight>
          <weight targetnode="10">1</weight>
      </node>
      <node nodeidx="9">
          <weight targetnode="10">1</weight>
      </node>
  </graph>
  <events>
          <move alpha="0.1" beta="0.1" delta="0.6"/>
        <evaporation eta="2.0" rho="10.0"/>
    </events>
</simulation>
